### ISSUE TITLE
SQLSTATE[22007]: Invalid datetime format - saving an image

### ISSUE THREAD

**Issue by maki3000** [mcharytoniuk/octobercms-headless#6]
Hello,
When I try to save an image, I get following SQL-error:
```
"SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'e3d0950a-1eb9-4bf7-8211-385a9bf49042' for column 'attachment_id' at row 1 (SQL: update `system_files` set `field` = backgroundImage, `attachment_id` = e3d0950a-1eb9-4bf7-8211-385a9bf49042, `attachment_type` = Newride\Headless\Models\StaticContent, `system_files`.`updated_at` = 2021-11-25 14:58:42 where `id` = 3)" on line 669 of D:\Web-Root\WS-Root\hiwoz\vendor\laravel\framework\src\Illuminate\Database\Connection.php
```
Here's my fields.yaml:
```
fields:
  backgroundImage:
    label: Hintergrundbild
    type: fileupload
    mode: image
    imageHeight: 420
    imageWidth: 640
    required: true
    span: left
    thumbOptions:
      mode: crop
  backgroundImage_mobile:
    label: Hintergrundbild Mobile
    type: fileupload
    mode: image
    imageHeight: 420
    imageWidth: 320
    required: true
    span: right
    thumbOptions:
      mode: crop
```
I don't know if I did something wrong with my setup...
